### ISSUE TITLE
Specified Key too long with opentaxii-create-services

### ISSUE THREAD

**Issue by combobulator** [MISP/MISP-Taxii-Server#2]
Hi,

I've been following your guide and everything was honkey dorey until I hit the portion to create tables for opentaxii. I hope you can help, or point me in the right direction :)

# Summary
Specifically, this command fails:
`opentaxii-create-services -c config/services.yaml`
The following command also fails:
`opentaxii-create-collections -c config/collections.yaml`

The traceback ends similarly for both (same error - full traceback at bottom of post):
> sqlalchemy.exc.OperationalError: (_mysql_exceptions.OperationalError) (1071, 'Specified key was too long; max key length is 767 bytes') [SQL: '\nCREATE TABLE accounts (\n\tid INTEGER NOT NULL AUTO_INCREMENT, \n\tusername VARCHAR(256), \n\tpassword_hash VARCHAR(256), \n\tPRIMARY KEY (id), \n\tUNIQUE (username)\n)\n\n']

I'm using MySQL Ver 15.1 in a [MISP Docker](https://github.com/harvard-itsecurity/docker-misp) container:
>\# mysql --version
mysql  Ver 15.1 Distrib 10.0.29-MariaDB, for debian-linux-gnu (x86_64) using readline 5.2

# Databases
Here's my databases as they exist at the moment:
>MariaDB [(none)]> show databases;
+--------------------+
| Database           |
+--------------------+
| information_schema |
| misp               |
| mysql              |
| performance_schema |
| taxiiauth          |
| taxiipersist       |
+--------------------+
6 rows in set (0.00 sec)
>
>MariaDB [(none)]> show tables from taxiipersist;
+-----------------------------+
| Tables_in_taxiipersist      |
+-----------------------------+
| collection_to_content_block |
| content_blocks              |
| data_collections            |
| inbox_messages              |
| result_sets                 |
| service_to_collection       |
| services                    |
| subscriptions               |
+-----------------------------+
8 rows in set (0.00 sec)
>
> MariaDB [(none)]> show tables from taxiiauth;
Empty set (0.00 sec)`

I'm no expert in MySQL, but after some digging around I thought this might be due to utf8mb4 encoding reducing the max key length, but both the taxii databases are in utf8 already:
>MariaDB [(none)]> SELECT default_character_set_name FROM information_schema.SCHEMATA S WHERE schema_name = "taxiipersist";
+----------------------------+
| default_character_set_name |
+----------------------------+
| utf8                       |
+----------------------------+
1 row in set (0.00 sec)
MariaDB [(none)]> SELECT default_character_set_name FROM information_schema.SCHEMATA S WHERE schema_name = "taxiiauth";
+----------------------------+
| default_character_set_name |
+----------------------------+
| utf8                       |
+----------------------------+
1 row in set (0.00 sec)

The misp database is in utf8mb4, but I assume this is irrelevant to the opentaxii databases:
> MariaDB [(none)]> SELECT default_character_set_name FROM information_schema.SCHEMATA S WHERE schema_name = "misp";
+----------------------------+
| default_character_set_name |
+----------------------------+
| utf8mb4                    |
+----------------------------+
1 row in set (0.00 sec)

Here's the rest of the MySQL encoding options I could find:
> MariaDB [(none)]> SHOW VARIABLES LIKE 'character_set%';
+--------------------------+----------------------------+
| Variable_name            | Value                      |
+--------------------------+----------------------------+
| character_set_client     | utf8mb4                    |
| character_set_connection | utf8mb4                    |
| character_set_database   | utf8mb4                    |
| character_set_filesystem | binary                     |
| character_set_results    | utf8mb4                    |
| character_set_server     | utf8mb4                    |
| character_set_system     | utf8                       |
| character_sets_dir       | /usr/share/mysql/charsets/ |
+--------------------------+----------------------------+
8 rows in set (0.00 sec)

# Tracebacks
`opentaxii-create-services -c config/services.yaml`
>\# opentaxii-create-services -c config/services.yaml
2017-03-28T10:31:31.164099Z [opentaxii.utils] info: api.initialized {event=api.initialized, timestamp=2017-03-28T10:31:31.164099Z, level=info, api=opentaxii.persistence.sqldb.SQLDatabaseAPI, logger=opentaxii.utils}
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/SQLAlchemy-1.1.7-py3.5-linux-x86_64.egg/sqlalchemy/engine/base.py", line 1182, in _execute_context
    context)
  File "/usr/local/lib/python3.5/dist-packages/SQLAlchemy-1.1.7-py3.5-linux-x86_64.egg/sqlalchemy/engine/default.py", line 470, in do_execute
    cursor.execute(statement, parameters)
  File "/usr/lib/python3/dist-packages/MySQLdb/cursors.py", line 226, in execute
    self.errorhandler(self, exc, value)
  File "/usr/lib/python3/dist-packages/MySQLdb/connections.py", line 36, in defaulterrorhandler
    raise errorvalue
  File "/usr/lib/python3/dist-packages/MySQLdb/cursors.py", line 217, in execute
    res = self._query(query)
  File "/usr/lib/python3/dist-packages/MySQLdb/cursors.py", line 378, in _query
    rowcount = self._do_query(q)
  File "/usr/lib/python3/dist-packages/MySQLdb/cursors.py", line 341, in _do_query
    db.query(q)
  File "/usr/lib/python3/dist-packages/MySQLdb/connections.py", line 280, in query
    _mysql.connection.query(self, query)
_mysql_exceptions.OperationalError: (1071, 'Specified key was too long; max key length is 767 bytes')
>
>The above exception was the direct cause of the following exception:
>
>Traceback (most recent call last):
  File "/usr/local/bin/opentaxii-create-services", line 9, in <module>
    load_entry_point('opentaxii==0.1.8a1', 'console_scripts', 'opentaxii-create-services')()
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 542, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 2569, in load_entry_point
    return ep.load()
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 2229, in load
    return self.resolve()
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 2235, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/usr/local/lib/python3.5/dist-packages/opentaxii-0.1.8a1-py3.5.egg/opentaxii/cli/__init__.py", line 10, in <module>
    server = TAXIIServer(config)
  File "/usr/local/lib/python3.5/dist-packages/opentaxii-0.1.8a1-py3.5.egg/opentaxii/server.py", line 40, in __init__
    api=initialize_api(config['auth_api']))
  File "/usr/local/lib/python3.5/dist-packages/opentaxii-0.1.8a1-py3.5.egg/opentaxii/utils.py", line 36, in initialize_api
    instance = cls(**params)
  File "/usr/local/lib/python3.5/dist-packages/opentaxii-0.1.8a1-py3.5.egg/opentaxii/auth/sqldb/api.py", line 41, in __init__
    self.db.create_all_tables()
  File "/usr/local/lib/python3.5/dist-packages/opentaxii-0.1.8a1-py3.5.egg/opentaxii/sqldb_helper.py", line 60, in create_all_tables
    self.metadata.create_all(bind=self.engine)
  File "/usr/local/lib/python3.5/dist-packages/SQLAlchemy-1.1.7-py3.5-linux-x86_64.egg/sqlalchemy/sql/schema.py", line 3885, in create_all
    tables=tables)
  File "/usr/local/lib/python3.5/dist-packages/SQLAlchemy-1.1.7-py3.5-linux-x86_64.egg/sqlalchemy/engine/base.py", line 1921, in _run_visitor
    conn._run_visitor(visitorcallable, element, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/SQLAlchemy-1.1.7-py3.5-linux-x86_64.egg/sqlalchemy/engine/base.py", line 1530, in _run_visitor
    **kwargs).traverse_single(element)
  File "/usr/local/lib/python3.5/dist-packages/SQLAlchemy-1.1.7-py3.5-linux-x86_64.egg/sqlalchemy/sql/visitors.py", line 121, in traverse_single
    return meth(obj, **kw)
  File "/usr/local/lib/python3.5/dist-packages/SQLAlchemy-1.1.7-py3.5-linux-x86_64.egg/sqlalchemy/sql/ddl.py", line 733, in visit_metadata
    _is_metadata_operation=True)
  File "/usr/local/lib/python3.5/dist-packages/SQLAlchemy-1.1.7-py3.5-linux-x86_64.egg/sqlalchemy/sql/visitors.py", line 121, in traverse_single
    return meth(obj, **kw)
  File "/usr/local/lib/python3.5/dist-packages/SQLAlchemy-1.1.7-py3.5-linux-x86_64.egg/sqlalchemy/sql/ddl.py", line 767, in visit_table
    include_foreign_key_constraints=include_foreign_key_constraints
  File "/usr/local/lib/python3.5/dist-packages/SQLAlchemy-1.1.7-py3.5-linux-x86_64.egg/sqlalchemy/engine/base.py", line 945, in execute
    return meth(self, multiparams, params)
  File "/usr/local/lib/python3.5/dist-packages/SQLAlchemy-1.1.7-py3.5-linux-x86_64.egg/sqlalchemy/sql/ddl.py", line 68, in _execute_on_connection
    return connection._execute_ddl(self, multiparams, params)
  File "/usr/local/lib/python3.5/dist-packages/SQLAlchemy-1.1.7-py3.5-linux-x86_64.egg/sqlalchemy/engine/base.py", line 1002, in _execute_ddl
    compiled
  File "/usr/local/lib/python3.5/dist-packages/SQLAlchemy-1.1.7-py3.5-linux-x86_64.egg/sqlalchemy/engine/base.py", line 1189, in _execute_context
    context)
  File "/usr/local/lib/python3.5/dist-packages/SQLAlchemy-1.1.7-py3.5-linux-x86_64.egg/sqlalchemy/engine/base.py", line 1394, in _handle_dbapi_exception
    exc_info
  File "/usr/local/lib/python3.5/dist-packages/SQLAlchemy-1.1.7-py3.5-linux-x86_64.egg/sqlalchemy/util/compat.py", line 203, in raise_from_cause
    reraise(type(exception), exception, tb=exc_tb, cause=cause)
  File "/usr/local/lib/python3.5/dist-packages/SQLAlchemy-1.1.7-py3.5-linux-x86_64.egg/sqlalchemy/util/compat.py", line 186, in reraise
    raise value.with_traceback(tb)
  File "/usr/local/lib/python3.5/dist-packages/SQLAlchemy-1.1.7-py3.5-linux-x86_64.egg/sqlalchemy/engine/base.py", line 1182, in _execute_context
    context)
  File "/usr/local/lib/python3.5/dist-packages/SQLAlchemy-1.1.7-py3.5-linux-x86_64.egg/sqlalchemy/engine/default.py", line 470, in do_execute
    cursor.execute(statement, parameters)
  File "/usr/lib/python3/dist-packages/MySQLdb/cursors.py", line 226, in execute
    self.errorhandler(self, exc, value)
  File "/usr/lib/python3/dist-packages/MySQLdb/connections.py", line 36, in defaulterrorhandler
    raise errorvalue
  File "/usr/lib/python3/dist-packages/MySQLdb/cursors.py", line 217, in execute
    res = self._query(query)
  File "/usr/lib/python3/dist-packages/MySQLdb/cursors.py", line 378, in _query
    rowcount = self._do_query(q)
  File "/usr/lib/python3/dist-packages/MySQLdb/cursors.py", line 341, in _do_query
    db.query(q)
  File "/usr/lib/python3/dist-packages/MySQLdb/connections.py", line 280, in query
    _mysql.connection.query(self, query)
sqlalchemy.exc.OperationalError: (_mysql_exceptions.OperationalError) (1071, 'Specified key was too long; max key length is 767 bytes') [SQL: '\nCREATE TABLE accounts (\n\tid INTEGER NOT NULL AUTO_INCREMENT, \n\tusername VARCHAR(256), \n\tpassword_hash VARCHAR(256), \n\tPRIMARY KEY (id), \n\tUNIQUE (username)\n)\n\n']

`# opentaxii-create-collections -c config/collections.yaml`
>2017-03-28T10:31:39.951289Z [opentaxii.utils] info: api.initialized {timestamp=2017-03-28T10:31:39.951289Z, api=opentaxii.persistence.sqldb.SQLDatabaseAPI, logger=opentaxii.utils, level=info, event=api.initialized}
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/SQLAlchemy-1.1.7-py3.5-linux-x86_64.egg/sqlalchemy/engine/base.py", line 1182, in _execute_context
    context)
  File "/usr/local/lib/python3.5/dist-packages/SQLAlchemy-1.1.7-py3.5-linux-x86_64.egg/sqlalchemy/engine/default.py", line 470, in do_execute
    cursor.execute(statement, parameters)
  File "/usr/lib/python3/dist-packages/MySQLdb/cursors.py", line 226, in execute
    self.errorhandler(self, exc, value)
  File "/usr/lib/python3/dist-packages/MySQLdb/connections.py", line 36, in defaulterrorhandler
    raise errorvalue
  File "/usr/lib/python3/dist-packages/MySQLdb/cursors.py", line 217, in execute
    res = self._query(query)
  File "/usr/lib/python3/dist-packages/MySQLdb/cursors.py", line 378, in _query
    rowcount = self._do_query(q)
  File "/usr/lib/python3/dist-packages/MySQLdb/cursors.py", line 341, in _do_query
    db.query(q)
  File "/usr/lib/python3/dist-packages/MySQLdb/connections.py", line 280, in query
    _mysql.connection.query(self, query)
_mysql_exceptions.OperationalError: (1071, 'Specified key was too long; max key length is 767 bytes')
>
>The above exception was the direct cause of the following exception:
>
>Traceback (most recent call last):
  File "/usr/local/bin/opentaxii-create-collections", line 9, in <module>
    load_entry_point('opentaxii==0.1.8a1', 'console_scripts', 'opentaxii-create-collections')()
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 542, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 2569, in load_entry_point
    return ep.load()
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 2229, in load
    return self.resolve()
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 2235, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/usr/local/lib/python3.5/dist-packages/opentaxii-0.1.8a1-py3.5.egg/opentaxii/cli/__init__.py", line 10, in <module>
    server = TAXIIServer(config)
  File "/usr/local/lib/python3.5/dist-packages/opentaxii-0.1.8a1-py3.5.egg/opentaxii/server.py", line 40, in __init__
    api=initialize_api(config['auth_api']))
  File "/usr/local/lib/python3.5/dist-packages/opentaxii-0.1.8a1-py3.5.egg/opentaxii/utils.py", line 36, in initialize_api
    instance = cls(**params)
  File "/usr/local/lib/python3.5/dist-packages/opentaxii-0.1.8a1-py3.5.egg/opentaxii/auth/sqldb/api.py", line 41, in __init__
    self.db.create_all_tables()
  File "/usr/local/lib/python3.5/dist-packages/opentaxii-0.1.8a1-py3.5.egg/opentaxii/sqldb_helper.py", line 60, in create_all_tables
    self.metadata.create_all(bind=self.engine)
  File "/usr/local/lib/python3.5/dist-packages/SQLAlchemy-1.1.7-py3.5-linux-x86_64.egg/sqlalchemy/sql/schema.py", line 3885, in create_all
    tables=tables)
  File "/usr/local/lib/python3.5/dist-packages/SQLAlchemy-1.1.7-py3.5-linux-x86_64.egg/sqlalchemy/engine/base.py", line 1921, in _run_visitor
    conn._run_visitor(visitorcallable, element, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/SQLAlchemy-1.1.7-py3.5-linux-x86_64.egg/sqlalchemy/engine/base.py", line 1530, in _run_visitor
    **kwargs).traverse_single(element)
  File "/usr/local/lib/python3.5/dist-packages/SQLAlchemy-1.1.7-py3.5-linux-x86_64.egg/sqlalchemy/sql/visitors.py", line 121, in traverse_single
    return meth(obj, **kw)
  File "/usr/local/lib/python3.5/dist-packages/SQLAlchemy-1.1.7-py3.5-linux-x86_64.egg/sqlalchemy/sql/ddl.py", line 733, in visit_metadata
    _is_metadata_operation=True)
  File "/usr/local/lib/python3.5/dist-packages/SQLAlchemy-1.1.7-py3.5-linux-x86_64.egg/sqlalchemy/sql/visitors.py", line 121, in traverse_single
    return meth(obj, **kw)
  File "/usr/local/lib/python3.5/dist-packages/SQLAlchemy-1.1.7-py3.5-linux-x86_64.egg/sqlalchemy/sql/ddl.py", line 767, in visit_table
    include_foreign_key_constraints=include_foreign_key_constraints
  File "/usr/local/lib/python3.5/dist-packages/SQLAlchemy-1.1.7-py3.5-linux-x86_64.egg/sqlalchemy/engine/base.py", line 945, in execute
    return meth(self, multiparams, params)
  File "/usr/local/lib/python3.5/dist-packages/SQLAlchemy-1.1.7-py3.5-linux-x86_64.egg/sqlalchemy/sql/ddl.py", line 68, in _execute_on_connection
    return connection._execute_ddl(self, multiparams, params)
  File "/usr/local/lib/python3.5/dist-packages/SQLAlchemy-1.1.7-py3.5-linux-x86_64.egg/sqlalchemy/engine/base.py", line 1002, in _execute_ddl
    compiled
  File "/usr/local/lib/python3.5/dist-packages/SQLAlchemy-1.1.7-py3.5-linux-x86_64.egg/sqlalchemy/engine/base.py", line 1189, in _execute_context
    context)
  File "/usr/local/lib/python3.5/dist-packages/SQLAlchemy-1.1.7-py3.5-linux-x86_64.egg/sqlalchemy/engine/base.py", line 1394, in _handle_dbapi_exception
    exc_info
  File "/usr/local/lib/python3.5/dist-packages/SQLAlchemy-1.1.7-py3.5-linux-x86_64.egg/sqlalchemy/util/compat.py", line 203, in raise_from_cause
    reraise(type(exception), exception, tb=exc_tb, cause=cause)
  File "/usr/local/lib/python3.5/dist-packages/SQLAlchemy-1.1.7-py3.5-linux-x86_64.egg/sqlalchemy/util/compat.py", line 186, in reraise
    raise value.with_traceback(tb)
  File "/usr/local/lib/python3.5/dist-packages/SQLAlchemy-1.1.7-py3.5-linux-x86_64.egg/sqlalchemy/engine/base.py", line 1182, in _execute_context
    context)
  File "/usr/local/lib/python3.5/dist-packages/SQLAlchemy-1.1.7-py3.5-linux-x86_64.egg/sqlalchemy/engine/default.py", line 470, in do_execute
    cursor.execute(statement, parameters)
  File "/usr/lib/python3/dist-packages/MySQLdb/cursors.py", line 226, in execute
    self.errorhandler(self, exc, value)
  File "/usr/lib/python3/dist-packages/MySQLdb/connections.py", line 36, in defaulterrorhandler
    raise errorvalue
  File "/usr/lib/python3/dist-packages/MySQLdb/cursors.py", line 217, in execute
    res = self._query(query)
  File "/usr/lib/python3/dist-packages/MySQLdb/cursors.py", line 378, in _query
    rowcount = self._do_query(q)
  File "/usr/lib/python3/dist-packages/MySQLdb/cursors.py", line 341, in _do_query
    db.query(q)
  File "/usr/lib/python3/dist-packages/MySQLdb/connections.py", line 280, in query
    _mysql.connection.query(self, query)
sqlalchemy.exc.OperationalError: (_mysql_exceptions.OperationalError) (1071, 'Specified key was too long; max key length is 767 bytes') [SQL: '\nCREATE TABLE accounts (\n\tid INTEGER NOT NULL AUTO_INCREMENT, \n\tusername VARCHAR(256), \n\tpassword_hash VARCHAR(256), \n\tPRIMARY KEY (id), \n\tUNIQUE (username)\n)\n\n']

**Comment by FloatingGhost** [comment]
I know this exact error - this is due to an old version of MySQL. 

I think MySQL 5.6 fixed this issue - I don't know which version of mariadb this relates to though.

Try running an update on the container and see if it works

**Comment by combobulator** [comment]
Thanks for your help, updating MariaDB to 10.1 from 10.0 fixed the issue.
For posterity my versions are now:
`mysql  Ver 15.1 Distrib 10.1.22-MariaDB, for debian-linux-gnu (x86_64) using readline 5.2`

For anyone else that stumbles on this page, the steps I took:
`# apt-get install software-properties-common`
`# apt-key adv --recv-keys --keyserver hkp://keyserver.ubuntu.com:80 0xF1656F24C74CD1D8`
`# add-apt-repository 'deb [arch=amd64,i386,ppc64el] http://mirrors.coreix.net/mariadb/repo/10.1/ubuntu xenial main'`
`# apt-get update && apt-get upgrade`
`# apt-get install`
`# apt-get install mysql-common mariadb-common libmysqlclient18 libmariadbclient18 mariadb-client-core-10.1 mariadb-client-10.1 mariadb-server-core-10.1 mariadb-server-10.1 libmariadbclient-dev mariadb-server`

I've now got another problem though, same command, different error :(
It occurs with the standard 'services.yaml' as well as with my edited version.
It strikes me that this may be more suited to the OpenTAXII issues page; happy to close this and move over there but first wanted to check if you'd come across it before.

>\# opentaxii-create-services -c services.yaml
2017-03-29T10:17:37.716675Z [opentaxii.utils] info: api.initialized {timestamp=2017-03-29T10:17:37.716675Z, event=api.initialized, api=opentaxii.persistence.sqldb.SQLDatabaseAPI, level=info, logger=opentaxii.utils}
2017-03-29T10:17:37.738597Z [opentaxii.utils] info: api.initialized {timestamp=2017-03-29T10:17:37.738597Z, event=api.initialized, api=opentaxii.auth.sqldb.SQLDatabaseAPI, level=info, logger=opentaxii.utils}
2017-03-29T10:17:37.738820Z [opentaxii.server] info: taxiiserver.configured {timestamp=2017-03-29T10:17:37.738820Z, event=taxiiserver.configured, logger=opentaxii.server, level=info}
Loading: services.yaml
Traceback (most recent call last):
  File "/usr/local/bin/opentaxii-create-services", line 9, in <module>
    load_entry_point('opentaxii==0.1.8a1', 'console_scripts', 'opentaxii-create-services')()
  File "/usr/local/lib/python3.5/dist-packages/opentaxii-0.1.8a1-py3.5.egg/opentaxii/cli/persistence.py", line 23, in create_services
    services_config = anyconfig.load(args.config, forced_type="yaml")
  File "/usr/local/lib/python3.5/dist-packages/anyconfig-0.9.1-py3.5.egg/anyconfig/api.py", line 377, in load
  File "/usr/local/lib/python3.5/dist-packages/anyconfig-0.9.1-py3.5.egg/anyconfig/api.py", line 262, in single_load
  File "/usr/local/lib/python3.5/dist-packages/anyconfig-0.9.1-py3.5.egg/anyconfig/backend/base.py", line 290, in load
  File "/usr/local/lib/python3.5/dist-packages/anyconfig-0.9.1-py3.5.egg/anyconfig/backend/base.py", line 424, in load_from_path
  File "/usr/local/lib/python3.5/dist-packages/anyconfig-0.9.1-py3.5.egg/anyconfig/backend/base.py", line 75, in wrapper
  File "/usr/local/lib/python3.5/dist-packages/anyconfig-0.9.1-py3.5.egg/anyconfig/backend/yaml.py", line 167, in _yml_load
ValueError: dictionary update sequence element #0 has length 9; 2 is required

**Comment by FloatingGhost** [comment]
```
_yml_load
ValueError: dictionary update sequence element #0 has length 9; 2 is required
```

this sounds like you have a bad yaml file - any chance you could post your `services.yaml` here if you've changed it?

**Comment by combobulator** [comment]
Tried each of the attached. services.yaml is exactly as it was when I cloned the repo, my.services just has changed descriptions. Had to add .txt to upload here

[my.services.yaml.txt](https://github.com/MISP/MISP-Taxii-Server/files/878724/my.services.yaml.txt)
[services.yaml.txt](https://github.com/MISP/MISP-Taxii-Server/files/878725/services.yaml.txt)

**Comment by FloatingGhost** [comment]
That's very weird. I'm using the same version of opentaxii as you, and the create-services script runs just fine with your config. 

However, I do appear to be using `anyconfig v0.7.0`.

Ah here we go. I get the same error as you now if I swap to anyconfig 0.9.1. 

I'll see if they updated opentaxii to be compatible with this new version

**Comment by FloatingGhost** [comment]
Ok, there you go - pushed a commit that updates OpenTaxii and gives a slightly different config file. That should fix it for you :)

**Comment by combobulator** [comment]
Awesomesauce, thanks, I'll check it out now and report back :)

**Comment by Danko90** [comment]
Hello,
I had the same error and I fixed it by putting the string 
```
services:
```
at the top in config/services.yaml

Did it work for you even without that string?

**Comment by FloatingGhost** [comment]
Well obviously, otherwise I'd have put that in

**Comment by ventz** [comment]
Running into similar issue with mariadb-server-10.1:

```
sqlalchemy.exc.InternalError: (pymysql.err.InternalError) (1071, 'Specified key was too long; max key length is 767 bytes') [SQL: 'CREATE UNIQUE INDEX ix_data_collections_name ON data_collections (name)']
```

I don't want to create a new issue since it seems related?

Error caused simply by running default: `opentaxii-sync-data config/data-configuration.yaml`
