### ISSUE TITLE
Status code 504 on taxii push

### ISSUE THREAD

**Issue by hendejos** [MISP/MISP-Taxii-Server#20]
Hi There,

Kinda new at this. When testing if my taxii server can push, it responds with:

2017-10-17 15:10:40,869 INFO: Sending Inbox_Message to http://localhost:9000/services/inbox
2017-10-17 15:10:40,998 ERROR: HTTP Error: status code 504

Command (also tried with user/pass)
"taxii-push --path http://localhost:9000/services/inbox -f sample.xml"

Please help on getting by this error. Thanks

**Comment by FloatingGhost** [comment]
504 is an HTTP timeout

Weird when accessing localhost, but it's probably a binding issues.

What happens on the server log? Does it say it has a connection

1. run `taxii-push --path http://localhost:9000/services/inbox -f sample.xml -v`  (the `-v` puts your client into verbose mode)
2. See what it says
3. see what the server says (if anything)

**Comment by hendejos** [comment]
Thanks for the help! I was able to troubleshoot my proxy settings and I was able to fix this issue. 

However, now I am getting this response:

2017-10-18 14:36:22,141 cabby.dispatcher DEBUG: Response:
<taxii_11:Status_Message xmlns:taxii="http://taxii.mitre.org/messages/taxii_xml_binding-1" xmlns:taxii_11="http://taxii.mitre.org/messages/taxii_xml_binding-1.1" xmlns:tdq="http://taxii.mitre.org/query/taxii_default_query-1" message_id="151022075200491629" in_response_to="0" status_type="UNAUTHORIZED"/>

2017-10-18 14:36:22,142 cabby.cli.commons ERROR: UNAUTHORIZED:

Is this just wrong username/password provided in push command?

Thanks!!

**Comment by FloatingGhost** [comment]
ah yeah, that's just a username/password issue

Make sure you've created the account with `opentaxii-create-account`, then use that username/password and you'll be golden

**Comment by hendejos** [comment]
Thanks again! I am getting closer.. now I am running into this:


 File "/usr/local/lib/python3.5/dist-packages/opentaxii-0.1.9a1-py3.5.egg/opent                                                                                     axii/utils.py", line 46, in parse_basic_auth_token
    print("'{}'".format(token), len(token))
OSError: [Errno 5] Input/output error


Verbose outputs the sample.xml, http code with Werkzeug, then tracebacks (with the error above.) Then finally cabby response (below).


2017-10-19 10:17:57,296 cabby.cli.commons ERROR: HTTP Error: status code 500
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/cabby/cli/commons.py", line 164,                                                                                      in run_client
    run_func(client, args.uri, args)
  File "/usr/local/lib/python3.5/dist-packages/cabby/cli/push.py", line 51, in _                                                                                     runner
    client.push(content, binding, collection_names=args.collections, uri=path)
  File "/usr/local/lib/python3.5/dist-packages/cabby/client11.py", line 332, in                                                                                      push
    service_type=const.SVC_INBOX)
  File "/usr/local/lib/python3.5/dist-packages/cabby/abstract.py", line 202, in                                                                                      _execute_request
    taxii_binding=self.taxii_binding)
  File "/usr/local/lib/python3.5/dist-packages/cabby/dispatcher.py", line 66, in                                                                                      send_taxii_request
    raise_http_error(response.status_code, response.raw)
  File "/usr/local/lib/python3.5/dist-packages/cabby/dispatcher.py", line 30, in                                                                                      raise_http_error
    raise HTTPError(status_code)
cabby.exceptions.HTTPError: HTTP Error: status code 500


Can you please help out?
Thanks

**Comment by FloatingGhost** [comment]
OS error 5 is "access denied"

What. In opentaxii!?

Hm, that seems to be an old version of opentaxii, can you try this

```
git pull
git submodule init
git submodule update
sudo python3 setup.py install
cd OpenTaxii
sudo python3 setup.py install
cd ..
# Run as normal
```

should make sure you're at the latest version

**Comment by FloatingGhost** [comment]
Nothing for over a month, closing as inactive, Will re-open if needed.

**Comment by hendejos** [comment]
Hi 
I had to start working on other things and now I'm back on this. 
Seems to be that I am on the latest versions, I ran the commands above. 

I am getting this now:

```
2018-01-10 11:58:20,852 urllib3.connectionpool DEBUG: Starting new HTTP connection (1): localhost
'bWlzcDphZG1pbg==' 16
127.0.0.1 - - [10/Jan/2018 11:58:20] "POST /services/inbox HTTP/1.1" 404 -
2018-01-10 11:58:20,908 urllib3.connectionpool DEBUG: http://localhost:9000 "POST /services/inbox HTTP/1.1" 404 233
2018-01-10 11:58:20,909 cabby.dispatcher DEBUG: Response:
<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 3.2 Final//EN">
<title>404 Not Found</title>
<h1>Not Found</h1>
<p>The requested URL was not found on the server.  If you entered the URL manually please check your spelling and try again.</p>

2018-01-10 11:58:20,910 cabby.cli.commons ERROR: HTTP Error: status code 404
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/cabby/cli/commons.py", line 171, in run_client
    run_func(client, args.uri, args)
  File "/usr/local/lib/python3.6/dist-packages/cabby/cli/push.py", line 51, in _runner
    client.push(content, binding, collection_names=args.collections, uri=path)
  File "/usr/local/lib/python3.6/dist-packages/cabby/client11.py", line 332, in push
    service_type=const.SVC_INBOX)
  File "/usr/local/lib/python3.6/dist-packages/cabby/abstract.py", line 205, in _execute_request
    timeout=self.timeout)
  File "/usr/local/lib/python3.6/dist-packages/cabby/dispatcher.py", line 70, in send_taxii_request
    raise_http_error(response.status_code, response.raw)
  File "/usr/local/lib/python3.6/dist-packages/cabby/dispatcher.py", line 33, in raise_http_error
    raise HTTPError(status_code)
cabby.exceptions.HTTPError: HTTP Error: status code 404
```

Any suggestions? Thanks!!

**Comment by FloatingGhost** [comment]
That is most certainly not the Opentaxii 404 message. You have something else running on port 9000.

**Comment by hendejos** [comment]
When I run **opentaxii-run-dev &** it says 

 Running on http://127.0.0.1:9000/ (Press CTRL+C to quit)

This is whats listening on port 9000

tcp        0      0 127.0.0.1:9000          0.0.0.0:*               LISTEN      **941/python3**

Does this look right? Not sure what else could be running on 9000.
