### ISSUE TITLE
cabby.cli.commons ERROR: FAILURE: There was a failure while executing the message handler

### ISSUE THREAD

**Issue by faustus25** [MISP/MISP-Taxii-Server#28]
Trying to push  a 70+MB file to MISP with OpenTaxii but fails with the following error message:

taxii-push --path http://localhost:9000/services/inbox -f lmx2.xml -v --dest collection --username xxxx --password xxxx

`2017-11-07  urllib3.connectionpool DEBUG: Starting new HTTP connection (1): localhost
2017-11-07  urllib3.connectionpool DEBUG: http://localhost:9000 "POST /services/inbox HTTP/1.1" 200 457
2017-11-07  cabby.dispatcher DEBUG: Response:
<taxii_11:Status_Message xmlns:taxii="http://taxii.mitre.org/messages/taxii_xml_binding-1" xmlns:taxii_11="http://taxii.mitre.org/messages/taxii_xml_binding-1.1" xmlns:tdq="http://taxii.mitre.org/query/taxii_default_query-1" message_id="8116567896521802236" in_response_to="1a5b1228-d28e-4d54-aae9-8470e3e6c275" status_type="FAILURE">
  <taxii_11:Message>There was a failure while executing the message handler</taxii_11:Message>
</taxii_11:Status_Message>

2017-11-07 cabby.cli.commons ERROR: FAILURE: There was a failure while executing the message handler
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/cabby-0.1.18-py3.5.egg/cabby/cli/commons.py", line 171, in run_client
    run_func(client, args.uri, args)
  File "/usr/local/lib/python3.5/dist-packages/cabby-0.1.18-py3.5.egg/cabby/cli/push.py", line 51, in _runner
    client.push(content, binding, collection_names=args.collections, uri=path)
  File "/usr/local/lib/python3.5/dist-packages/cabby-0.1.18-py3.5.egg/cabby/client11.py", line 332, in push
    service_type=const.SVC_INBOX)
  File "/usr/local/lib/python3.5/dist-packages/cabby-0.1.18-py3.5.egg/cabby/abstract.py", line 205, in _execute_request
    timeout=self.timeout)
  File "/usr/local/lib/python3.5/dist-packages/cabby-0.1.18-py3.5.egg/cabby/dispatcher.py", line 91, in send_taxii_request
    raise UnsuccessfulStatusError(obj)
cabby.exceptions.UnsuccessfulStatusError: FAILURE: There was a failure while executing the message handler
`
Error from OpenTaxii Server:
`
  File "src/lxml/etree.pyx", line 3441, in lxml.etree.parse
  File "src/lxml/parser.pxi", line 1855, in lxml.etree._parseDocument
  File "src/lxml/parser.pxi", line 1875, in lxml.etree._parseFilelikeDocument
  File "src/lxml/parser.pxi", line 1770, in lxml.etree._parseDocFromFilelike
  File "src/lxml/parser.pxi", line 1185, in lxml.etree._BaseParser._parseDocFromFilelike
  File "src/lxml/parser.pxi", line 598, in lxml.etree._ParserContext._handleParseResultDoc
  File "src/lxml/parser.pxi", line 709, in lxml.etree._handleParseResult
  File "src/lxml/parser.pxi", line 638, in lxml.etree._raiseParseError
opentaxii.taxii.exceptions.FailureStatus: AttValue: ' expected, line 610, column 891 (<string>, line 610)}
127.0.0.1 - - [07/Nov/2017] "POST /services/inbox HTTP/1.1" 200 -
`
File itself:

-rw-r--r--  1 root root 70435985 Nov  2 17:52 lmx2.xml

Can the file size be an issue with limit on size of pushed file (FSISAC STIX File)?
Or other?

**Comment by FloatingGhost** [comment]
how am I supposed to know? 

I can't test it without knowing what you tried to convert.

Christ some people, is it *THAT* hard to allow me to replicate your issues?

**Comment by FloatingGhost** [comment]
Going with repo policy, raising an issue without any sort of test data to replicate means I'm closing this.

Please don't do it again.

**Comment by faustus25** [comment]
It is an FSISAC repo pull file with 680,000 lines of which most would have to be redacted. (Yes, due to the TLP concept some STIX files can't be shared in their entirety!)

I will extract the some of the content to high the impacted string which is causing the push to fail:
`
  File "src/lxml/etree.pyx", line 3441, in lxml.etree.parse
  File "src/lxml/parser.pxi", line 1855, in lxml.etree._parseDocument
  File "src/lxml/parser.pxi", line 1875, in lxml.etree._parseFilelikeDocument
  File "src/lxml/parser.pxi", line 1770, in lxml.etree._parseDocFromFilelike
  File "src/lxml/parser.pxi", line 1185, in lxml.etree._BaseParser._parseDocFromFilelike
  File "src/lxml/parser.pxi", line 598, in lxml.etree._ParserContext._handleParseResultDoc
  File "src/lxml/parser.pxi", line 709, in lxml.etree._handleParseResult
  File "src/lxml/parser.pxi", line 638, in lxml.etree._raiseParseError
opentaxii.taxii.exceptions.FailureStatus: AttValue: ' expected, line 610, column 891 (<string>, line 610), timestamp=2017-11-08, event=Status exception, logger=opentaxii.middleware, level=warning}
127.0.0.1 - - [08/Nov/2017 ] "POST /services/inbox HTTP/1.1" 200 -
  File "src/lxml/etree.pyx", line 3441, in lxml.etree.parse
  File "src/lxml/parser.pxi", line 1855, in lxml.etree._parseDocument
  File "src/lxml/parser.pxi", line 1875, in lxml.etree._parseFilelikeDocument
  File "src/lxml/parser.pxi", line 1770, in lxml.etree._parseDocFromFilelike
  File "src/lxml/parser.pxi", line 1185, in lxml.etree._BaseParser._parseDocFromFilelike
  File "src/lxml/parser.pxi", line 598, in lxml.etree._ParserContext._handleParseResultDoc
  File "src/lxml/parser.pxi", line 709, in lxml.etree._handleParseResult
  File "src/lxml/parser.pxi", line 638, in lxml.etree._raiseParseError
opentaxii.taxii.exceptions.FailureStatus: AttValue: ' expected, line 610, column 891 (<string>, line 610), timestamp=2017-11-08, event=Status exception, logger=opentaxii.middleware, level=warning}
127.0.0.1 - - [08/Nov/2017 ] "POST /services/inbox HTTP/1.1" 200 -
`
SEE LINE BELOW (line 610, column 891) `
`
<taxii_11:Content_Block xmlns:soltra="http://taxii.soltra.com/messages/taxii_extension_xml_binding-1.1" xmlns:taxii="http://taxii.mitre.org/messages/taxii_xml_binding-1" xmlns:taxii_11="http://taxii.mitre.org/messages/taxii_xml_binding-1.1" xmlns:tdq="http://taxii.mitre.org/query/taxii_default_query-1"><taxii_11:Content_Binding binding_id="urn:stix.mitre.org:xml:1.1.1"/><taxii_11:Content><stix:STIX_Package xmlns:cyboxCommon="http://cybox.mitre.org/common-2" xmlns:cybox="http://cybox.mitre.org/cybox-2" xmlns:cyboxVocabs="http://cybox.mitre.org/default_vocabularies-2" xmlns:marking="http://data-marking.mitre.org/Marking-1" xmlns:tlpMarking="http://data-marking.mitre.org/extensions/MarkingStructure#TLP-1" xmlns:TOUMarking="http://data-marking.mitre.org/extensions/MarkingStructure#Terms_Of_Use-1" xmlns:maecBundle="http://maec.mitre.org/XMLSchema/maec-bundle-4" xmlns:maecPackage="http://maec.mitre.org/XMLSchema/maec-package-2" xmlns:maecVocabs="http://maec.mitre.org/default_vocabularies-1" xmlns:edge="http://soltra.com/" xmlns:ttp="http://stix.mitre.org/TTP-1" xmlns:stixCommon="http://stix.mitre.org/common-1" xmlns:stixVocabs="http://stix.mitre.org/default_vocabularies-1" xmlns:stix-maec="http://stix.mitre.org/extensions/Malware#MAEC4.1-1" xmlns:stix="http://stix.mitre.org/stix-1" xmlns:NCCIC="http://www.us-cert.gov/" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" id="edge:Package-351a3b61-b421-4ad4-b2dd-ccc121370f3c" version="1.1.1" timestamp="2017-11-02T17:50:15.019957+00:00">
`
Specific field it calls out: (In column 891 is between "ht" 891"tp"
xmlns:maecPackage="**http**://maec.mitre.org/XMLSchema/maec-package-2"

I can redact the specific content block for that code if you want to test it.
