### ISSUE TITLE
"ERROR: FAILURE: There was a failure while executing the message handler"

### ISSUE THREAD

**Issue by advancedeng** [MISP/MISP-Taxii-Server#33]
Getting this annoying generic error message, just can't put my finger on it if it has to do with hooks.py or something else. Here are the details, hope I haven't missed anything. Appreciate your help!

Config file:
[config.txt](https://github.com/MISP/MISP-Taxii-Server/files/1603746/config.txt)

**Command run:**
taxii-push --path http://localhost:9000/services/inbox -f sample.xml -v     
    \    --dest collection --username xxxxx --password xxxxx

**Output:**
...
2018-01-04 15:20:16,560 urllib3.connectionpool DEBUG: Starting new HTTP connection (1): localhost
2018-01-04 15:20:16,669 urllib3.connectionpool DEBUG: http://localhost:9000 "POST /services/inbox HTTP/1.1" 200 457
2018-01-04 15:20:16,670 cabby.dispatcher DEBUG: Response:
<taxii_11:Status_Message xmlns:taxii="http://taxii.mitre.org/messages/taxii_xml_binding-1" xmlns:taxii_11="http://taxii.mitre.org/messages/taxii_xml_binding-1.1" xmlns:tdq="http://taxii.mitre.org/query/taxii_default_query-1" message_id="5995687554560328764" in_response_to="70e3d7d8-6098-4b3b-9a38-b61c4912a94d" status_type="FAILURE">
  <taxii_11:Message>There was a failure while executing the message handler</taxii_11:Message>
</taxii_11:Status_Message>

2018-01-04 15:20:16,671 cabby.cli.commons ERROR: FAILURE: There was a failure while executing the message handler
Traceback (most recent call last):
  File "/usr/local/lib/python3.4/dist-packages/cabby-0.1.18-py3.4.egg/cabby/cli/commons.py", line 171, in run_client
    run_func(client, args.uri, args)
  File "/usr/local/lib/python3.4/dist-packages/cabby-0.1.18-py3.4.egg/cabby/cli/push.py", line 51, in _runner
    client.push(content, binding, collection_names=args.collections, uri=path)
  File "/usr/local/lib/python3.4/dist-packages/cabby-0.1.18-py3.4.egg/cabby/client11.py", line 332, in push
    service_type=const.SVC_INBOX)
  File "/usr/local/lib/python3.4/dist-packages/cabby-0.1.18-py3.4.egg/cabby/abstract.py", line 205, in _execute_request
    timeout=self.timeout)
  File "/usr/local/lib/python3.4/dist-packages/cabby-0.1.18-py3.4.egg/cabby/dispatcher.py", line 91, in send_taxii_request
    raise UnsuccessfulStatusError(obj)
cabby.exceptions.UnsuccessfulStatusError: FAILURE: There was a failure while executing the message handler

**Comment by advancedeng** [comment]
Sorry, it was the session issue. I ran the exports from scratch again (below) which seem to have fixed the issue.

_export OPENTAXII_CONFIG=/path/to/config.yaml
export PYTHONPATH=._

Thank you, appreciate your prompt reply.
