### ISSUE TITLE
Feed does not exist on run-taxii-poll

### ISSUE THREAD

**Issue by robertnixon2003** [MISP/MISP-Taxii-Server#37]
Whenever I run the remote poll script I get feed not found. But the feed does exisit when I pull it pull collections. What gives?

collection_information_client respoinse:

```
Message Type: Collection_Information_Request
Message ID: 6863940986663948709

Response:

Message Type: Collection_Information_Response
Message ID: 748964006333316359; In Response To: 6863940986663948709
Contains 2 Collection Informations
  === Data Collection Information ===
    Collection Name: system.Default
    Collection Type: DATA_FEED
    Available: True
    Collection Description: system.Default
    Supported Content:     urn:stix.mitre.org:xml:1.0
    === Polling Service Instance ===
      Poll Protocol: urn:taxii.mitre.org:protocol:https:1.0
      Poll Address: https://xxx.xxx.xxx.xxx/taxii-data
      Message Binding: urn:taxii.mitre.org:message:xml:1.1
  ==================================

  === Data Collection Information ===
    Collection Name: ronixon.past7days
    Collection Type: DATA_FEED
    Available: True
    Collection Description: ronixon.past7days
    Supported Content:     urn:stix.mitre.org:xml:1.0
    === Polling Service Instance ===
      Poll Protocol: urn:taxii.mitre.org:protocol:https:1.0
      Poll Address: https://xxx.xxx.xxx.xxx/taxii-data
      Message Binding: urn:taxii.mitre.org:message:xml:1.1
  ==================================

```
Error on run-taxii-poll.py

```

2018-01-31 17:16:38,497 - __main__ - DEBUG - Polling collection ronixon.past7days
2018-01-31 17:16:39,237 - __main__ - ERROR - FAILED TO POLL collection ronixon.past7days
2018-01-31 17:16:39,237 - __main__ - ERROR - NOT_FOUND: Feed not found
Traceback (most recent call last):
  File "./run-taxii-poll.py", line 103, in <module>
    for content_block in cli.poll(collection_name=collection):
  File "/usr/local/lib/python3.5/dist-packages/cabby/client11.py", line 485, in poll
    service_type=const.SVC_POLL)
  File "/usr/local/lib/python3.5/dist-packages/cabby/abstract.py", line 205, in _execute_request
    timeout=self.timeout)
  File "/usr/local/lib/python3.5/dist-packages/cabby/dispatcher.py", line 91, in send_taxii_request
    raise UnsuccessfulStatusError(obj)
cabby.exceptions.UnsuccessfulStatusError: NOT_FOUND: Feed not found
2018-01-31 17:16:39,239 - __main__ - INFO - Finished!

```

**Comment by FloatingGhost** [comment]
Can't really help here, I know the client *does* work with custom collection names, but without knowledge of how your system (and the server's system) is set up, I've no hope of ever debugging it.
