### ISSUE TITLE
Automated TAXII -> MISP Sync Poll Failed

### ISSUE THREAD

**Issue by Nymeria1** [MISP/MISP-Taxii-Server#48]
Hello,
I have a problem during the execution of sync from TAXII to MISP.

The taxii-discovery and taxii-poll command from CLI works without problem.

Below the log from poll.log file

 

> __main__ - ERROR - FAILED TO PUSH BLOCK!
> 2018-04-09 07:06:59,067 - __main__ - ERROR - <cabby.entities.ContentBlock object at 0x7fe213138cc0>
> 2018-04-09 07:06:59,067 - __main__ - ERROR - FAILURE: There was a failure while executing the message handler
> Traceback (most recent call last):
>   File "run-taxii-poll.py", line 147, in <module>
>     uri=localInbox)
>   File "/usr/local/lib/python3.5/dist-packages/cabby/client11.py", line 332, in push
>     service_type=const.SVC_INBOX)
>   File "/usr/local/lib/python3.5/dist-packages/cabby/abstract.py", line 190, in _execute_request
>     timeout=self.timeout)
>   File "/usr/local/lib/python3.5/dist-packages/cabby/dispatcher.py", line 63, in send_taxii_request
>     raise UnsuccessfulStatusError(obj)
> cabby.exceptions.UnsuccessfulStatusError: FAILURE: There was a failure while executing the message handler

Many thanks for your help

**Comment by Nymeria1** [comment]
Ok I find the slution.
Update STIX/Cybox library without considering the diagnostic information. In this way I do not have the handler error.
