### ISSUE TITLE
Test push - status 404

### ISSUE THREAD

**Issue by shimi199393** [MISP/MISP-Taxii-Server#54]
I run the script for test after insall and get respone code 404 :
taxii-push --path http://localhost:9000/services/inbox -f test.xml \
--dest collection --username root --password root

Traceback (most recent call last): File "/usr/local/lib/python3.6/dist-packages/cabby/cli/commons.py", line 171, in run_client run_func(client, args.uri, args) File "/usr/local/lib/python3.6/dist-packages/cabby/cli/push.py", line 51, in _runner client.push(content, binding, collection_names=args.collections, uri=path) File "/usr/local/lib/python3.6/dist-packages/cabby/client11.py", line 332, in push service_type=const.SVC_INBOX) File "/usr/local/lib/python3.6/dist-packages/cabby/abstract.py", line 205, in _execute_request timeout=self.timeout) File "/usr/local/lib/python3.6/dist-packages/cabby/dispatcher.py", line 70, in send_taxii_request raise_http_error(response.status_code, response.raw) File "/usr/local/lib/python3.6/dist-packages/cabby/dispatcher.py", line 33, in raise_http_error raise HTTPError(status_code) cabby.exceptions.HTTPError: HTTP Error: status code 404
I try everything . Thanks

**Comment by FloatingGhost** [comment]
![image](https://user-images.githubusercontent.com/4086403/47383995-db5a5380-d6fd-11e8-8683-a3df7156d77d.png)
