### ISSUE TITLE
Hooks Config Issue - NameError: name 'config' is not defined

### ISSUE THREAD

**Issue by maddog317** [MISP/MISP-Taxii-Server#6]
The following command cannot be run when no changes were made to the services file.
    `opentaxii-create-services -c config/services.yaml`

It fails on the following function in the hooks.py file
```
MISP = pymisp.PyMISP(
                        CONFIG["misp"]["url"],
                        CONFIG["misp"]["api"],
                        ssl = config["misp"].get("verifySSL", True) #line 43
                )
```

The hooks config error is shown below:
```
opentaxii-create-services -c config/services.yaml
2017-05-22T14:57:48.486818Z [opentaxii.utils] info: api.initialized {event=api.initialized, timestamp=2017-05-22T14:57:48.486818Z, api=opentaxii.persistence.sqldb.SQLDatabaseAPI, logger=opentaxii.utils, level=info}
2017-05-22T14:57:48.497640Z [opentaxii.utils] info: api.initialized {event=api.initialized, timestamp=2017-05-22T14:57:48.497640Z, api=opentaxii.auth.sqldb.SQLDatabaseAPI, logger=opentaxii.utils, level=info}
Using config from /home/ubuntu/MISP-Taxii-Server/config/config.yaml
Traceback (most recent call last):
  File "/usr/local/bin/opentaxii-create-services", line 9, in <module>
    load_entry_point('opentaxii==0.1.9a1', 'console_scripts', 'opentaxii-create-services')()
  File "/usr/lib/python3/dist-packages/pkg_resources.py", line 351, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/usr/lib/python3/dist-packages/pkg_resources.py", line 2363, in load_entry_point
    return ep.load()
  File "/usr/lib/python3/dist-packages/pkg_resources.py", line 2088, in load
    entry = __import__(self.module_name, globals(),globals(), ['__name__'])
  File "/usr/local/lib/python3.4/dist-packages/opentaxii-0.1.9a1-py3.4.egg/opentaxii/cli/__init__.py", line 10, in <module>
    server = TAXIIServer(config)
  File "/usr/local/lib/python3.4/dist-packages/opentaxii-0.1.9a1-py3.4.egg/opentaxii/server.py", line 45, in __init__
    importlib.import_module(signal_hooks)
  File "/usr/lib/python3.4/importlib/__init__.py", line 109, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 2254, in _gcd_import
  File "<frozen importlib._bootstrap>", line 2237, in _find_and_load
  File "<frozen importlib._bootstrap>", line 2226, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 1191, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 1161, in _load_backward_compatible
  File "/usr/local/lib/python3.4/dist-packages/misp_taxii_hooks-0.2-py3.4.egg/misp_taxii_hooks/hooks.py", line 43, in <module>
NameError: name 'config' is not defined
```

**Comment by FloatingGhost** [comment]
Quite right. Fixed.
