### ISSUE TITLE
MISP-Taxii-Server crashes when trying to connect to a MISP instance with a self signed certificate

### ISSUE THREAD

**Issue by worldopener** [MISP/MISP-Taxii-Server#61]
Using MISP with a self signed certificate leads to crash of the Taxii-Server

I followed the installation doc but i get this error when i try to create the services

```
# opentaxii-create-services -c config/services.yaml
2019-01-16T14:38:02.474182Z [opentaxii.utils] info: api.initialized {logger=opentaxii.utils, level=info, api=opentaxii.persistence.sqldb.SQLDatabaseAPI, event=api.initialized, timestamp=2019-01-16T14:38:02.474182Z}
2019-01-16T14:38:02.525408Z [opentaxii.utils] info: api.initialized {logger=opentaxii.utils, level=info, api=opentaxii.auth.sqldb.SQLDatabaseAPI, event=api.initialized, timestamp=2019-01-16T14:38:02.525408Z}
Using config from /var/www/Taxii-Server/config/config.yaml
Traceback (most recent call last):
  File "/var/www/Taxii-Server/venv/lib/python3.5/site-packages/urllib3/connectionpool.py", line 594, in urlopen
    self._prepare_proxy(conn)
  File "/var/www/Taxii-Server/venv/lib/python3.5/site-packages/urllib3/connectionpool.py", line 805, in _prepare_proxy
    conn.connect()
  File "/var/www/Taxii-Server/venv/lib/python3.5/site-packages/urllib3/connection.py", line 344, in connect
    ssl_context=context)
  File "/var/www/Taxii-Server/venv/lib/python3.5/site-packages/urllib3/util/ssl_.py", line 344, in ssl_wrap_socket
    return context.wrap_socket(sock, server_hostname=server_hostname)
  File "/usr/lib/python3.5/ssl.py", line 385, in wrap_socket
    _context=self)
  File "/usr/lib/python3.5/ssl.py", line 760, in __init__
    self.do_handshake()
  File "/usr/lib/python3.5/ssl.py", line 996, in do_handshake
    self._sslobj.do_handshake()
  File "/usr/lib/python3.5/ssl.py", line 641, in do_handshake
    self._sslobj.do_handshake()
ssl.SSLError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:720)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/var/www/Taxii-Server/venv/lib/python3.5/site-packages/requests/adapters.py", line 449, in send
    timeout=timeout
  File "/var/www/Taxii-Server/venv/lib/python3.5/site-packages/urllib3/connectionpool.py", line 638, in urlopen
    _stacktrace=sys.exc_info()[2])
  File "/var/www/Taxii-Server/venv/lib/python3.5/site-packages/urllib3/util/retry.py", line 398, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='misp.test.local', port=443): Max retries exceeded with url: /servers/getPyMISPVersion.json (Caused by SSLError(SSLError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:720)'),))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/var/www/Taxii-Server/venv/lib/python3.5/site-packages/pymisp/api.py", line 112, in __init__
    response = self.get_recommended_api_version()
  File "/var/www/Taxii-Server/venv/lib/python3.5/site-packages/pymisp/api.py", line 1099, in get_recommended_api_version
    response = session.get(url)
  File "/var/www/Taxii-Server/venv/lib/python3.5/site-packages/requests/sessions.py", line 546, in get
    return self.request('GET', url, **kwargs)
  File "/var/www/Taxii-Server/venv/lib/python3.5/site-packages/requests/sessions.py", line 533, in request
    resp = self.send(prep, **send_kwargs)
  File "/var/www/Taxii-Server/venv/lib/python3.5/site-packages/requests/sessions.py", line 668, in send
    history = [resp for resp in gen] if allow_redirects else []
  File "/var/www/Taxii-Server/venv/lib/python3.5/site-packages/requests/sessions.py", line 668, in <listcomp>
    history = [resp for resp in gen] if allow_redirects else []
  File "/var/www/Taxii-Server/venv/lib/python3.5/site-packages/requests/sessions.py", line 247, in resolve_redirects
    **adapter_kwargs
  File "/var/www/Taxii-Server/venv/lib/python3.5/site-packages/requests/sessions.py", line 646, in send
    r = adapter.send(request, **kwargs)
  File "/var/www/Taxii-Server/venv/lib/python3.5/site-packages/requests/adapters.py", line 514, in send
    raise SSLError(e, request=request)
requests.exceptions.SSLError: HTTPSConnectionPool(host='misp.test.local', port=443): Max retries exceeded with url: /servers/getPyMISPVersion.json (Caused by SSLError(SSLError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:720)'),))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/var/www/Taxii-Server/venv/bin/opentaxii-create-services", line 11, in <module>
    load_entry_point('opentaxii==0.1.10a1', 'console_scripts', 'opentaxii-create-services')()
  File "/var/www/Taxii-Server/venv/lib/python3.5/site-packages/pkg_resources/__init__.py", line 561, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/var/www/Taxii-Server/venv/lib/python3.5/site-packages/pkg_resources/__init__.py", line 2631, in load_entry_point
    return ep.load()
  File "/var/www/Taxii-Server/venv/lib/python3.5/site-packages/pkg_resources/__init__.py", line 2291, in load
    return self.resolve()
  File "/var/www/Taxii-Server/venv/lib/python3.5/site-packages/pkg_resources/__init__.py", line 2297, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/var/www/Taxii-Server/venv/lib/python3.5/site-packages/opentaxii-0.1.10a1-py3.5.egg/opentaxii/cli/__init__.py", line 10, in <module>
    server = TAXIIServer(config)
  File "/var/www/Taxii-Server/venv/lib/python3.5/site-packages/opentaxii-0.1.10a1-py3.5.egg/opentaxii/server.py", line 45, in __init__
    importlib.import_module(signal_hooks)
  File "/var/www/Taxii-Server/venv/lib/python3.5/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "/var/www/Taxii-Server/misp_taxii_hooks/hooks.py", line 47, in <module>
    ssl = CONFIG["misp"].get("verifySSL", True)
  File "/var/www/Taxii-Server/venv/lib/python3.5/site-packages/pymisp/api.py", line 126, in __init__
    raise PyMISPError('Unable to connect to MISP ({}). Please make sure the API key and the URL are correct (http/https is required): {}'.format(self.root_url, e))
pymisp.exceptions.PyMISPError: Unable to connect to MISP (http://misp.test.local). Please make sure the API key and the URL are correct (http/https is required): HTTPSConnectionPool(host='misp.test.local', port=443): Max retries exceeded with url: /servers/getPyMISPVersion.json (Caused by SSLError(SSLError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:720)'),))
```

**Comment by worldopener** [comment]
This fixes the error:

```
diff --git a/pymisp/api.py b/pymisp/api.py
index d68472a..d29b658 100644
--- a/pymisp/api.py
+++ b/pymisp/api.py
@@ -1096,7 +1096,7 @@ class PyMISP(object):
         """Returns the recommended API version from the server"""
         session = self.__prepare_session()
         url = urljoin(self.root_url, 'servers/getPyMISPVersion.json')
-        response = session.get(url)
+        response = session.get(url, verify=False)
         return self._check_response(response)

     def get_version(self):
```

I think the cleanest way to solve this, is to create a local CA

**Comment by FloatingGhost** [comment]
You shouldn't have to edit pymisp itself. It's already able to handle self-signed certficates.

See [the README](https://github.com/MISP/MISP-Taxii-Server#insecurerequestwarning)

As a last resort, you can disable SSL verification (config -> misp -> verifySSL), but this is not recommended.

**Comment by worldopener** [comment]
the CA is trusted as wget for example throws no errror

The README seems to be outdated because when i set

```
misp:
    url: "https://test.local"
    api: xxxx
    verifySSL = False
```
i get

```
  File "/var/www/Taxii-Server/venv/lib/python3.5/site-packages/yaml/scanner.py", line 289, in stale_possible_simple_keys
    "could not find expected ':'", self.get_mark())
yaml.scanner.ScannerError: while scanning a simple key
  in "/var/www/Taxii-Server/config/config.yaml", line 32, column 5
could not find expected ':'
  in "/var/www/Taxii-Server/config/config.yaml", line 34, column 1

```
Setting it with:

```
misp:
    url: "https://test.local"
    api: xxxx
    verifySSL: False
```

leads to the same error again
[SSL: CERTIFICATE_VERIFY_FAILED]

also exporting the CAs crt (i use an internal CA now) doesnt work

export REQUESTS_CA_BUNDLE=/usr/local/share/ca-certificates/CA.crt

Why doesn't it use the local certs wget uses?

**Comment by FloatingGhost** [comment]
```
verifySSL = False
```
well yeah of course this would fail? This is invalid YAML

>Why doesn't it use the local certs wget uses?

A question for the maintainers of `requests` rather than me, I'm afraid
