### ISSUE TITLE
Issue while polling the taxii feed

### ISSUE THREAD

**Issue by kknagesh** [MISP/MISP-Taxii-Server#69]
Hi, I am trying to run 
taxii-push -vvvvvvvv --path http://localhost:9000/services/inbox -f tests/test.xml --dest my_collection --username admin --password admin and i am getting the UNAUTHORIZED error 

2019-02-19 11:05:55,918 - __main__ - CRITICAL - Could not connect to local server
2019-02-19 11:05:55,918 - __main__ - CRITICAL - UNAUTHORIZED:
'YWRtaW46YWRtaW4=' 16
2019-02-19T11:08:16.942766Z [opentaxii.middleware] warning: Status exception {exception=Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/Flask-1.0.2-py3.6.egg/flask/app.py", line 1811, in full_dispatch_request
    rv = self.preprocess_request()
  File "/usr/local/lib/python3.6/dist-packages/Flask-1.0.2-py3.6.egg/flask/app.py", line 2087, in preprocess_request
    rv = func()
  File "/usr/local/lib/python3.6/dist-packages/opentaxii-0.1.11-py3.6.egg/opentaxii/middleware.py", line 59, in create_context_before_request
    context.account = _authenticate(server, request.headers)
  File "/usr/local/lib/python3.6/dist-packages/opentaxii-0.1.11-py3.6.egg/opentaxii/middleware.py", line 131, in _authenticate
    raise UnauthorizedException()
opentaxii.exceptions.UnauthorizedException: UNAUTHORIZED}

I have also exported the Open taxii config as well, database credentials are also validated. The open taxii process is also running

what are the credentials which we need to use in the user name and password and if we need to create one, can you please tell me where i can create them.

**Comment by FloatingGhost** [comment]
Accounts are configured in [data-configuration.yaml](https://github.com/MISP/MISP-Taxii-Server/blob/master/config/data-configuration.yaml#L61)

Did you run `opentaxii-sync-data config/data-configuration.yaml` (with `OPENTAXII_CONFIG` exported at the time)? That should create all of your accounts and such

**Comment by kknagesh** [comment]
Thanks !!!

**Comment by itsnotabhi** [comment]
I am getting the following error on my opentaxii run dev after running the poll script
I was trying to get feeds from a remote taxi system



2020-12-15T12:24:01.223820Z [opentaxii.middleware] warning: Status exception {exception=Traceback (most recent call last):
  File "/home/misp/.local/lib/python3.8/site-packages/flask/app.py", line 1948, in full_dispatch_request
    rv = self.preprocess_request()
  File "/home/misp/.local/lib/python3.8/site-packages/flask/app.py", line 2242, in preprocess_request
    rv = func()
  File "/home/misp/.local/lib/python3.8/site-packages/opentaxii/middleware.py", line 59, in create_context_before_request
    context.account = _authenticate(server, request.headers)
  File "/home/misp/.local/lib/python3.8/site-packages/opentaxii/middleware.py", line 138, in _authenticate
    raise UnauthorizedException(
opentaxii.exceptions.UnauthorizedException: UNAUTHORIZED}
2020-12-15T12:24:01.224914Z [werkzeug] info: 127.0.0.1 - - [15/Dec/2020 12:24:01] "POST /services/discovery HTTP/1.1" 200 -
