### ISSUE TITLE
Run-Taxii-Poll.py : 'NoneType' object has no attribute 'startswith'

### ISSUE THREAD

**Issue by GuilleAbad** [MISP/MISP-Taxii-Server#74]
I've been deploying the MISP-TAXII Server following the official steps, and in the MISP - TAXII Sync Phase i've had that curious error while running the script:

 root@mis-ioc-p-01a:~/MISP-Taxii-Server# /usr/bin/python /root/MISP-Taxii-Server/scripts/run-taxii-poll.py -v
/root/MISP-Taxii-Server/scripts/run-taxii-poll.py:54: YAMLLoadWarning: calling yaml.load() without Loader=... is deprecated, as the default Loader is unsafe. Please read https://msg.pyyaml.org/load for full details.
  config = yaml.load(f.read())
/root/MISP-Taxii-Server/scripts/run-taxii-poll.py:61: YAMLLoadWarning: calling yaml.load() without Loader=... is deprecated, as the default Loader is unsafe. Please read https://msg.pyyaml.org/load for full details.
  local_config = yaml.load(f.read())
Traceback (most recent call last):
  File "/root/MISP-Taxii-Server/scripts/run-taxii-poll.py", line 154, in <module>
    if not server_uri_override.startswith("http"):
AttributeError: 'NoneType' object has no attribute 'startswith'

As I have checked, this error shows up because the URI server that tries to get in the line before:
 server_uri_override = server.get("uri", None)
Gets the default value None (Second parameter of the get method) because of it cant catch anything while getting "uri".

It's that a bug of the py script, or i have missconfigured something? 

Remote server.yml:
- name: 'Remote Server'
  host: remotehost.com
  port: 443
  discovery_path: /discoverypath
  use_https: True
  taxii_version: '1.1'
  headers:
  auth:
    username: myusername
    password: mypassword
    cacert_path:
    cert_file:
    key_file:
    key_password:
    jwt_auth_url:
    verify_ssl: True
  collections:
   - remote_collection

I've run the run-taxii-poll.py script -v to have all log categories shown in Poll.log (+ server URI echo):
2019-04-01 12:47:21,928 - __main__ - DEBUG - Opening config file /root/.misptax$
2019-04-01 12:47:21,931 - __main__ - DEBUG - Config read [{'name': 'Remote Serve$
2019-04-01 12:47:21,931 - __main__ - DEBUG - Reading local server config
2019-04-01 12:47:21,935 - __main__ - INFO - Connecting to local server...
2019-04-01 12:47:21,989 - __main__ - INFO - Connected
2019-04-01 12:47:21,989 - __main__ - INFO - Set poll time to None - 2019-04-01 $
2019-04-01 12:47:21,989 - __main__ - INFO - == Remote Server ==
2019-04-01 12:47:21,989 - __main__ - DEBUG - Creating client
2019-04-01 12:47:21,989 - __main__ - DEBUG - HOST:PORT : remotehost.com:443
2019-04-01 12:47:21,990 - __main__ - DEBUG - DISCPATH: /discoverypath
2019-04-01 12:47:21,990 - __main__ - DEBUG - Setting client log level
2019-04-01 12:47:21,990 - __main__ - DEBUG - Setting authentication...
2019-04-01 12:47:21,990 - __main__ - DEBUG - Discovering services...
2019-04-01 12:47:22,557 - cabby.client11.Client11 - INFO - 3 services discovered
2019-04-01 12:47:22,558 - __main__ - DEBUG - [<cabby.entities.DetailedServiceIn$
2019-04-01 12:47:22,558 - __main__ - DEBUG - Auth set.
2019-04-01 12:47:22,558 - __main__ - DEBUG - Polling remote_collection
2019-04-01 12:47:22,558 - __main__ - DEBUG - Server URI None

I think i have provided all conf files that needed, if its necesary more info, please tell me.

Thanks in advance!

PS: I've tried using python2 and python3 and the result is the same, got same error.

**Comment by FloatingGhost** [comment]
it was an artefact from debugging someone else's issue

pull and try again

fixed via 2300977

**Comment by GuilleAbad** [comment]
Thanks for the pull, but it also continues crashing in the next uri the python needs:
Traceback (most recent call last):
  File "/root/MISP-Taxii-Server/scripts/run-taxii-poll.py", line 166, in <module>
    uri=server.get("uri", None)):
  File "/usr/local/lib/python2.7/dist-packages/cabby/client11.py", line 485, in poll
    service_type=const.SVC_POLL)
  File "/usr/local/lib/python2.7/dist-packages/cabby/abstract.py", line 190, in _execute_request
    timeout=self.timeout)
  File "/usr/local/lib/python2.7/dist-packages/cabby/dispatcher.py", line 63, in send_taxii_request
    raise UnsuccessfulStatusError(obj)
UnsuccessfulStatusError: NOT_FOUND: ITEM=remote_collection; Requested collection was not found

I've tried to change from None to "" in that server get but it didnt solved the problem. It seems that the py sends an empty URI where the process has to look for and poll from the collection, and if its None or "" it fails, because there's nothing there.

Thanks for the fast response!

**Comment by FloatingGhost** [comment]
```
Requested collection was not found
```

well that's pretty self-explanatory - it's not crashing at all, it's gracefully exiting as it can't find a collection called `remote_collection`. And not on my side either. Check your parameters.

Set the `-v` switch if you need to be sure.

**Comment by GuilleAbad** [comment]
Well yes, i've used bad words to refer to the error, it dont crash, but i'm lost with that server.get(uri), because of it cant catch anything because nothing related to uri is set as a variable in server object that can be picked by get method later. That's why the collection cant be found, its looking for the collection at "" or at None, right? Should server object need a variable that stores the poll and the collection-management paths?

I've been kicking off my head to a wall for some days thinking of it.

My collection name is well written in the remote server.yml, i've checked it again.

Thanks again :)

**Comment by FloatingGhost** [comment]
Provided you don't *set* uri, `None` will be thrown - this is intentional. Cabby will take this as a "not set" and ignore it. 

So no, it is *not* looking at `"" or None`, set the `-v` flag. Set it.

**Comment by GuilleAbad** [comment]
You're right... the collection is not there... i've made some days before a taxii-poll "arguments" "collection name" > report.xml to check the magnitude of the file i was trying to poll, it's possible that i've literally cut it from the server or it doesnt mind?

**Comment by GuilleAbad** [comment]
I've tried again (yesterday the collection dissapeared...) and got the next traceback:

root@mis-ioc-p-01a:~/MISP-Taxii-Server/scripts# /usr/bin/python run-taxii-poll.py -v

run-taxii-poll.py:54: YAMLLoadWarning: calling yaml.load() without Loader=... is deprecated, as the default Loader is unsafe. Please read https://msg.pyyaml.org/load for full details.
  config = yaml.load(f.read())
run-taxii-poll.py:61: YAMLLoadWarning: calling yaml.load() without Loader=... is deprecated, as the default Loader is unsafe. Please read https://msg.pyyaml.org/load for full details.
  local_config = yaml.load(f.read())
{"timestamp": "2019-04-03T08:00:41.033327Z", "logger": "__main__", "event": "Posting STIX...", "level": "info"}
{"level": "error", "timestamp": "2019-04-03T08:00:41.036671Z", "exc_info": ["<class 'lxml.etree.XMLSyntaxError'>", "XMLSyntaxError(u\"AttValue: ' expected, line 932, column 56\",)", "<traceback object at 0x7f64cc83d758>"], "logger": "flask.app", "event": "Exception on /services/inbox_swift [POST]"}
{"event": "Internal error", "timestamp": "2019-04-03T08:00:41.036812Z", "exception": "Traceback (most recent call last):\n  File \"/usr/local/lib/python2.7/dist-packages/flask/app.py\", line 2292, in wsgi_app\n    response = self.full_dispatch_request()\n  File \"/usr/local/lib/python2.7/dist-packages/flask/app.py\", line 1815, in full_dispatch_request\n    rv = self.handle_user_exception(e)\n  File \"/usr/local/lib/python2.7/dist-packages/flask/app.py\", line 1718, in handle_user_exception\n    reraise(exc_type, exc_value, tb)\n  File \"/usr/local/lib/python2.7/dist-packages/flask/app.py\", line 1813, in full_dispatch_request\n    rv = self.dispatch_request()\n  File \"/usr/local/lib/python2.7/dist-packages/flask/app.py\", line 1799, in dispatch_request\n    return self.view_functions[rule.endpoint](**req.view_args)\n  File \"/usr/local/lib/python2.7/dist-packages/opentaxii/middleware.py\", line 85, in wrapper\n    return _process_with_service(service)\n  File \"/usr/local/lib/python2.7/dist-packages/opentaxii/middleware.py\", line 163, in _process_with_service\n    response_message = service.process(request.headers, taxii_message)\n  File \"/usr/local/lib/python2.7/dist-packages/opentaxii/taxii/services/abstract.py\", line 83, in process\n    response_message = handler.handle_message(self, message)\n  File \"/usr/local/lib/python2.7/dist-packages/opentaxii/taxii/services/handlers/inbox_message_handlers.py\", line 123, in handle_message\n    return InboxMessage11Handler.handle_message(service, request)\n  File \"/usr/local/lib/python2.7/dist-packages/opentaxii/taxii/services/handlers/inbox_message_handlers.py\", line 63, in handle_message\n    inbox_message_id=inbox_message.id if inbox_message else None)\n  File \"/usr/local/lib/python2.7/dist-packages/opentaxii/persistence/manager.py\", line 197, in create_content\n    collection_ids=collection_ids, service_id=service_id)\n  File \"/usr/local/lib/python2.7/dist-packages/blinker/base.py\", line 267, in send\n    for receiver in self.receivers_for(sender)]\n  File \"/root/MISP-Taxii-Server/misp_taxii_hooks/hooks.py\", line 62, in post_stix\n    package = pymisp.tools.stix.load_stix(StringIO(block))\n  File \"/root/MISP-Taxii-Server/src/pymisp/pymisp/tools/stix.py\", line 16, in load_stix\n    stix = convert.load_stix(stix)\n  File \"/root/MISP-Taxii-Server/src/misp-stix-converter/misp_stix_converter/converters/convert.py\", line 121, in load_stix\n    stix_xml = etree.fromstring(stix.read())\n  File \"src/lxml/etree.pyx\", line 3222, in lxml.etree.fromstring\n  File \"src/lxml/parser.pxi\", line 1877, in lxml.etree._parseMemoryDocument\n  File \"src/lxml/parser.pxi\", line 1758, in lxml.etree._parseDoc\n  File \"src/lxml/parser.pxi\", line 1068, in lxml.etree._BaseParser._parseUnicodeDoc\n  File \"src/lxml/parser.pxi\", line 601, in lxml.etree._ParserContext._handleParseResultDoc\n  File \"src/lxml/parser.pxi\", line 711, in lxml.etree._handleParseResult\n  File \"src/lxml/parser.pxi\", line 640, in lxml.etree._raiseParseError\nXMLSyntaxError: AttValue: ' expected, line 932, column 56 (line 932)", "logger": "opentaxii.middleware", "level": "error"}
{"timestamp": "2019-04-03T08:00:41.360621Z", "logger": "__main__", "event": "Posting STIX...", "level": "info"}
{"level": "error", "timestamp": "2019-04-03T08:00:41.362430Z", "exc_info": ["<class 'lxml.etree.XMLSyntaxError'>", "XMLSyntaxError(u'Premature end of data in tag Hash line 954, line 956, column 6',)", "<traceback object at 0x7f64cc39ff38>"], "logger": "flask.app", "event": "Exception on /services/inbox_swift [POST]"}
{"event": "Internal error", "timestamp": "2019-04-03T08:00:41.362558Z", "exception": "Traceback (most recent call last):\n  File \"/usr/local/lib/python2.7/dist-packages/flask/app.py\", line 2292, in wsgi_app\n    response = self.full_dispatch_request()\n  File \"/usr/local/lib/python2.7/dist-packages/flask/app.py\", line 1815, in full_dispatch_request\n    rv = self.handle_user_exception(e)\n  File \"/usr/local/lib/python2.7/dist-packages/flask/app.py\", line 1718, in handle_user_exception\n    reraise(exc_type, exc_value, tb)\n  File \"/usr/local/lib/python2.7/dist-packages/flask/app.py\", line 1813, in full_dispatch_request\n    rv = self.dispatch_request()\n  File \"/usr/local/lib/python2.7/dist-packages/flask/app.py\", line 1799, in dispatch_request\n    return self.view_functions[rule.endpoint](**req.view_args)\n  File \"/usr/local/lib/python2.7/dist-packages/opentaxii/middleware.py\", line 85, in wrapper\n    return _process_with_service(service)\n  File \"/usr/local/lib/python2.7/dist-packages/opentaxii/middleware.py\", line 163, in _process_with_service\n    response_message = service.process(request.headers, taxii_message)\n  File \"/usr/local/lib/python2.7/dist-packages/opentaxii/taxii/services/abstract.py\", line 83, in process\n    response_message = handler.handle_message(self, message)\n  File \"/usr/local/lib/python2.7/dist-packages/opentaxii/taxii/services/handlers/inbox_message_handlers.py\", line 123, in handle_message\n    return InboxMessage11Handler.handle_message(service, request)\n  File \"/usr/local/lib/python2.7/dist-packages/opentaxii/taxii/services/handlers/inbox_message_handlers.py\", line 63, in handle_message\n    inbox_message_id=inbox_message.id if inbox_message else None)\n  File \"/usr/local/lib/python2.7/dist-packages/opentaxii/persistence/manager.py\", line 197, in create_content\n    collection_ids=collection_ids, service_id=service_id)\n  File \"/usr/local/lib/python2.7/dist-packages/blinker/base.py\", line 267, in send\n    for receiver in self.receivers_for(sender)]\n  File \"/root/MISP-Taxii-Server/misp_taxii_hooks/hooks.py\", line 62, in post_stix\n    package = pymisp.tools.stix.load_stix(StringIO(block))\n  File \"/root/MISP-Taxii-Server/src/pymisp/pymisp/tools/stix.py\", line 16, in load_stix\n    stix = convert.load_stix(stix)\n  File \"/root/MISP-Taxii-Server/src/misp-stix-converter/misp_stix_converter/converters/convert.py\", line 121, in load_stix\n    stix_xml = etree.fromstring(stix.read())\n  File \"src/lxml/etree.pyx\", line 3222, in lxml.etree.fromstring\n  File \"src/lxml/parser.pxi\", line 1877, in lxml.etree._parseMemoryDocument\n  File \"src/lxml/parser.pxi\", line 1758, in lxml.etree._parseDoc\n  File \"src/lxml/parser.pxi\", line 1068, in lxml.etree._BaseParser._parseUnicodeDoc\n  File \"src/lxml/parser.pxi\", line 601, in lxml.etree._ParserContext._handleParseResultDoc\n  File \"src/lxml/parser.pxi\", line 711, in lxml.etree._handleParseResult\n  File \"src/lxml/parser.pxi\", line 640, in lxml.etree._raiseParseError\nXMLSyntaxError: Premature end of data in tag Hash line 954, line 956, column 6 (line 956)", "logger": "opentaxii.middleware", "level": "error"}

Poll.log:

2019-04-03 08:00:35,305 - __main__ - DEBUG - Opening config file /root/.misptaxii/remote-servers.yml
2019-04-03 08:00:35,308 - __main__ - DEBUG - Config read [{'name': 'Remote SERVER', 'taxii_version': '1.1', 'auth': {'username': 'api_use$
2019-04-03 08:00:35,308 - __main__ - DEBUG - Reading local server config
2019-04-03 08:00:35,310 - __main__ - INFO - Connecting to local server...
2019-04-03 08:00:35,361 - __main__ - INFO - Connected
2019-04-03 08:00:35,361 - __main__ - INFO - Set poll time to None - 2019-04-03 08:00:35.361248+00:00
2019-04-03 08:00:35,361 - __main__ - INFO - == Remote Server ==
2019-04-03 08:00:35,361 - __main__ - DEBUG - Creating client
2019-04-03 08:00:35,361 - __main__ - DEBUG - HOST:PORT : remotehost:443
2019-04-03 08:00:35,361 - __main__ - DEBUG - DISCPATH: /discoverypath
2019-04-03 08:00:35,361 - __main__ - DEBUG - Setting client log level
2019-04-03 08:00:35,361 - __main__ - DEBUG - Setting authentication...
2019-04-03 08:00:35,361 - __main__ - DEBUG - Discovering services...
2019-04-03 08:00:36,208 - cabby.client11.Client11 - INFO - 3 services discovered
2019-04-03 08:00:36,208 - __main__ - DEBUG - [<cabby.entities.DetailedServiceInstance object at 0x7feff1c10150>, <cabby.entities.Detaile$
2019-04-03 08:00:36,208 - __main__ - DEBUG - Auth set.
2019-04-03 08:00:36,208 - __main__ - DEBUG - Polling remote_collection
2019-04-03 08:00:36,208 - __main__ - DEBUG - Server URI
2019-04-03 08:00:36,208 - __main__ - DEBUG - Within date range Beginning of time - 2019-04-03 08:00:35.361248+00:00
2019-04-03 08:00:38,718 - __main__ - DEBUG - Pushing block <cabby.entities.ContentBlock object at 0x7feff1c10450>
2019-04-03 08:00:41,064 - __main__ - ERROR - FAILED TO PUSH BLOCK!
2019-04-03 08:00:41,066 - __main__ - ERROR - <cabby.entities.ContentBlock object at 0x7feff1c10450>
2019-04-03 08:00:41,066 - __main__ - ERROR - FAILURE: Server error occurred
Traceback (most recent call last):
  File "run-taxii-poll.py", line 173, in <module>
    uri=local_inbox)
  File "/usr/local/lib/python2.7/dist-packages/cabby/client11.py", line 332, in push
    service_type=const.SVC_INBOX)
  File "/usr/local/lib/python2.7/dist-packages/cabby/abstract.py", line 190, in _execute_request
    timeout=self.timeout)
  File "/usr/local/lib/python2.7/dist-packages/cabby/dispatcher.py", line 63, in send_taxii_request
    raise UnsuccessfulStatusError(obj)
UnsuccessfulStatusError: FAILURE: Server error occurred
2019-04-03 08:00:41,154 - __main__ - DEBUG - Pushing block <cabby.entities.ContentBlock object at 0x7feff0ddacd0>
2019-04-03 08:00:41,378 - __main__ - ERROR - FAILED TO PUSH BLOCK!
2019-04-03 08:00:41,378 - __main__ - ERROR - <cabby.entities.ContentBlock object at 0x7feff0ddacd0>
2019-04-03 08:00:41,378 - __main__ - ERROR - FAILURE: Server error occurred
Traceback (most recent call last):
  File "run-taxii-poll.py", line 173, in <module>
    uri=local_inbox)
  File "/usr/local/lib/python2.7/dist-packages/cabby/client11.py", line 332, in push
    service_type=const.SVC_INBOX)
  File "/usr/local/lib/python2.7/dist-packages/cabby/abstract.py", line 190, in _execute_request
    timeout=self.timeout)
  File "/usr/local/lib/python2.7/dist-packages/cabby/dispatcher.py", line 63, in send_taxii_request
    raise UnsuccessfulStatusError(obj)
UnsuccessfulStatusError: FAILURE: Server error occurred
2019-04-03 08:00:41,380 - __main__ - INFO - Finished!

Any ideas?

thanks again @FloatingGhost :)
