### ISSUE TITLE
Taxii-push fails

### ISSUE THREAD

**Issue by m1357** [MISP/MISP-Taxii-Server#79]
when running the opentaxii-run-dev and trying the tests.xml push as defined in the documentation I get the following. The only change I made was to have the server run on port 6000 instead of 9000 as this is run on the same server as misp and port 9000 is used by php-fpm.

2020-04-15T20:56:29.881172Z [pymisp] critical: Unknown error: the response is not in JSON.
Something is broken server-side, please send us everything that follows (careful with the key):
Request headers:
{'User-Agent': 'PyMISP 2.4.124 - Python 3.6', 'Accept-Encoding': 'gzip, deflate', 'Accept': 'application/json', 'Connection': 'keep-alive', 'Content-Length': '291', 'Authorization': 'redacted', 'content-type': 'application/json'}
Request body:
{"values": "198.51.100.2", "returnFormat": "json", "withAttachments": 0, "metadata": 0, "enforceWarninglist": 0, "includeEventUuid": 0, "includeEventTags": 0, "sgReferenceOnly": 0, "includeContext": 0, "headerless": 0, "includeSightings": 0, "includeDecayScore": 0, "includeCorrelations": 0}
Response (if any):
<!DOCTYPE HTML PUBLIC "-//IETF//DTD HTML 2.0//EN">
<html><head>
<title>503 Service Unavailable</title>
</head><body>
<h1>Service Unavailable</h1>
<p>The server is temporarily unable to service your
request due to maintenance downtime or capacity
problems. Please try again later.</p>
</body></html>
 
2020-04-15T20:56:29.912686Z [werkzeug] info: 127.0.0.1 - - [15/Apr/2020 13:56:29] "POST /services/inbox HTTP/1.1" 500 - 
Traceback (most recent call last):
  File "/usr/local/lib64/python3.6/site-packages/flask/app.py", line 2464, in __call__
    return self.wsgi_app(environ, start_response)
  File "/usr/local/lib64/python3.6/site-packages/flask/app.py", line 2450, in wsgi_app
    response = self.handle_exception(e)
  File "/usr/local/lib64/python3.6/site-packages/flask/app.py", line 1867, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib64/python3.6/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/usr/local/lib64/python3.6/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib64/python3.6/site-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib64/python3.6/site-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib64/python3.6/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/usr/local/lib64/python3.6/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib64/python3.6/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/usr/local/lib/python3.6/site-packages/opentaxii/middleware.py", line 85, in wrapper
    return _process_with_service(service)
  File "/usr/local/lib/python3.6/site-packages/opentaxii/middleware.py", line 163, in _process_with_service
    response_message = service.process(request.headers, taxii_message)
  File "/usr/local/lib/python3.6/site-packages/opentaxii/taxii/services/abstract.py", line 83, in process
    response_message = handler.handle_message(self, message)
  File "/usr/local/lib/python3.6/site-packages/opentaxii/taxii/services/handlers/inbox_message_handlers.py", line 123, in handle_message
    return InboxMessage11Handler.handle_message(service, request)
  File "/usr/local/lib/python3.6/site-packages/opentaxii/taxii/services/handlers/inbox_message_handlers.py", line 63, in handle_message
    inbox_message_id=inbox_message.id if inbox_message else None)
  File "/usr/local/lib/python3.6/site-packages/opentaxii/persistence/manager.py", line 197, in create_content
    collection_ids=collection_ids, service_id=service_id)
  File "/usr/local/lib/python3.6/site-packages/blinker/base.py", line 267, in send
    for receiver in self.receivers_for(sender)]
  File "/usr/local/lib/python3.6/site-packages/blinker/base.py", line 267, in <listcomp>
    for receiver in self.receivers_for(sender)]
  File "/opt/app/MISP-Taxii-Server/misp_taxii_hooks/hooks.py", line 68, in post_stix
    search = MISP.search("attributes", values=str(attrib))
  File "/opt/app/MISP-Taxii-Server/src/pymisp/pymisp/api.py", line 1524, in search
    normalized_response = self._check_json_response(response)
  File "/opt/app/MISP-Taxii-Server/src/pymisp/pymisp/api.py", line 2160, in _check_json_response
    r = self._check_response(response, expect_json=True)
  File "/opt/app/MISP-Taxii-Server/src/pymisp/pymisp/api.py", line 2169, in _check_response
    raise MISPServerError(f'Error code 500:\n{response.text}')
pymisp.exceptions.MISPServerError: Error code 500:
<!DOCTYPE HTML PUBLIC "-//IETF//DTD HTML 2.0//EN">
<html><head>
<title>503 Service Unavailable</title>
</head><body>
<h1>Service Unavailable</h1>
<p>The server is temporarily unable to service your
request due to maintenance downtime or capacity
problems. Please try again later.</p>
</body></html>

**Comment by FloatingGhost** [comment]
your misp instance is down or unreachable. misp configuration is beyond the scope of this repository.

**Comment by itsnotabhi** [comment]
When tried pushing test files as per the guide to my newly setup taxii server, it returns the error ERROR: HTTP Error: status code 500
